"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Loader2, ArrowLeft, Download, Share2 } from "lucide-react";
import { apiGet } from "@/lib/api";

type WatchlistEntry = {
  slug?: string;
  name: string;
  score: number;
  issues?: string[];
  ai_note?: string;
};

export default function WatchlistPage() {
  const [entries, setEntries] = useState<WatchlistEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    apiGet("/v1/county/watchlist")
      .then((data) => setEntries(Array.isArray(data) ? data : data?.watchlist ?? []))
      .catch(() => setEntries([]))
      .finally(() => setLoading(false));
  }, []);

  const critical = entries.filter((e) => e.score < 50).sort((a, b) => a.score - b.score);
  const good = entries.filter((e) => e.score >= 50).sort((a, b) => b.score - a.score);

  function download() {
    const blob = new Blob([JSON.stringify(entries, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "weekly-watchlist.json";
    a.click();
    URL.revokeObjectURL(url);
  }

  async function share() {
    const summary = critical.map((c) => `${c.name}: ${c.score}/100`).join("\n");
    try {
      await navigator.clipboard.writeText(`Weekly Watchlist\n\n${summary}`);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // clipboard unavailable, ignore
    }
  }

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <Link href="/county" className="flex items-center gap-1 text-sm font-medium text-stone-500 hover:text-amber-900">
        <ArrowLeft size={14} /> Back to Dashboard
      </Link>

      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold text-stone-900">Weekly Watchlist</h1>
          <p className="text-sm text-stone-500">Auto-generated by Gemma 4 - {new Date().toLocaleDateString()}</p>
        </div>
        <div className="flex gap-2">
          <button onClick={download} className="clay-btn-secondary flex items-center gap-1 rounded-xl px-3 py-2 text-sm">
            <Download size={14} /> Download Report
          </button>
          <button onClick={share} className="clay-btn-secondary flex items-center gap-1 rounded-xl px-3 py-2 text-sm">
            <Share2 size={14} /> {copied ? "Copied!" : "Share with Ministry"}
          </button>
        </div>
      </div>

      {loading ? (
        <div className="flex items-center gap-2 text-sm text-stone-500"><Loader2 size={16} className="animate-spin" /> Loading watchlist...</div>
      ) : (
        <>
          <div className="clay-card space-y-4 p-6">
            <h2 className="font-bold text-red-700">Requires Immediate Attention ({critical.length})</h2>
            {critical.length === 0 ? (
              <p className="text-sm text-stone-500">No facilities in crisis this week.</p>
            ) : (
              critical.map((e) => (
                <div key={e.name} className="clay-card-flat space-y-2 rounded-2xl p-4">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-stone-900">{e.name}</span>
                    <span className="text-sm font-bold text-red-600">Score: {e.score}</span>
                  </div>
                  <div className="clay-progress-track h-2.5 w-full">
                    <div className="h-full rounded-full bg-red-500" style={{ width: `${e.score}%` }} />
                  </div>
                  {e.issues && e.issues.length > 0 && (
                    <ul className="list-inside list-disc text-sm text-stone-600">
                      {e.issues.map((issue, i) => (
                        <li key={i}>{issue}</li>
                      ))}
                    </ul>
                  )}
                  {e.ai_note && <p className="text-sm italic text-stone-500">Gemma 4: {e.ai_note}</p>}
                  {e.slug && (
                    <Link href={`/county/hospitals/${e.slug}`} className="inline-block text-sm font-semibold text-amber-800 hover:underline">
                      View -&gt;
                    </Link>
                  )}
                </div>
              ))
            )}
          </div>

          <div className="clay-card space-y-2 p-6">
            <h2 className="font-bold text-green-700">Performing Well</h2>
            <div className="flex flex-wrap gap-2">
              {good.map((e) => (
                <span key={e.name} className="clay-pill clay-card-flat px-3 py-1.5 text-sm text-stone-700">
                  {e.name} - {e.score}
                </span>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
